import Sparticles from "sparticles";

let pokeRain = new Sparticles({
    minSize: 20,
    maxSize: 70,
    count: 200,
    minAlpha: 1,
    maxAlpha: 1,
    drift: 0,
    direction: 180,
    rotation: 2,
    xVariance: 10,
    parallax: 2,
    speed: 1,
    shape: ["image", "circle"],
    imageUrl: [
      "https://img.pokemondb.net/sprites/items/poke-ball.png",
      "https://img.pokemondb.net/sprites/items/poke-ball.png",
      "https://img.pokemondb.net/sprites/items/poke-ball.png",
      "https://img.pokemondb.net/sprites/items/poke-ball.png",
      "https://img.pokemondb.net/sprites/items/poke-ball.png",
      "https://img.pokemondb.net/sprites/items/poke-ball.png",
      "https://img.pokemondb.net/sprites/items/poke-ball.png",
      "https://img.pokemondb.net/sprites/items/poke-ball.png",
      "https://img.pokemondb.net/sprites/items/poke-ball.png",
      "https://img.pokemondb.net/sprites/items/poke-ball.png",
      "https://img.pokemondb.net/sprites/items/great-ball.png",
      "https://img.pokemondb.net/sprites/items/ultra-ball.png",
      "https://img.pokemondb.net/sprites/items/master-ball.png",
      "https://img.pokemondb.net/sprites/items/friend-ball.png",
      "https://img.pokemondb.net/sprites/items/fast-ball.png",
      "https://img.pokemondb.net/sprites/items/dream-ball.png",
      "https://img.pokemondb.net/sprites/items/dive-ball.png",
      "https://img.pokemondb.net/sprites/items/level-ball.png",
      "https://img.pokemondb.net/sprites/items/lure-ball.png",
      "https://img.pokemondb.net/sprites/items/love-ball.png",
      "https://img.pokemondb.net/sprites/items/moon-ball.png",
      "https://img.pokemondb.net/sprites/items/nest-ball.png",
      "https://img.pokemondb.net/sprites/items/net-ball.png",
      "https://img.pokemondb.net/sprites/items/park-ball.png",
      "https://img.pokemondb.net/sprites/items/premier-ball.png",
      "https://img.pokemondb.net/sprites/items/quick-ball.png",
      "https://img.pokemondb.net/sprites/items/safari-ball.png",
      "https://img.pokemondb.net/sprites/items/sport-ball.png",
      "https://img.pokemondb.net/sprites/items/timer-ball.png",
    ],
    color: ["transparent"]
  });

  export default pokeRain